version: "3"

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "cluster_status" ]
      interval: 10s
      timeout: 30s
      retries: 6
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672

  ai-predictor:
    build: .
    container_name: ai-predictor
    volumes:
      - .:/ai-predictor
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - TOKEN_URL=$TOKEN_URL
      - CLIENT_SECRET=$CLIENT_SECRET
      - USERNAME=$USERNAME
      - PASSWORD=$PASSWORD
      - CLIENT_ID=$CLIENT_ID
      - PATCH_ANNOTATIONS_URL=$PATCH_ANNOTATIONS_URL
      - RABBITMQ_HOST=$RABBITMQ_HOST
      - RABBITMQ_PORT=$RABBITMQ_PORT
      - RABBITMQ_QUEUE=$RABBITMQ_QUEUE
      - RABBITMQ_HEARTBEAT=$RABBITMQ_HEARTBEAT
      - VERBOSITY=$VERBOSITY
